Jenkinsfile, test/data/compose/docker-compose.oauth.yml, test/data/compose/docker-compose.yml, test/data/config/config_remote.json, test/data/config/config_testcontainers.json, test/messaging_service_test.go, test/oauth_test.go, test/persistent_receiver_test.go, test/sempclient/Dockerfile, test/sempclient/makeclean, test/sempclient/semp-client.go, test/sempclient/spec/spec_action.json, test/sempclient/spec/spec_config.json, test/sempclient/spec/spec_monitor.json, test/testcontext/config.go, test/testcontext/test_context.go
Changes for SOL-86282
Including changes for SOL-89100, SOL-88870 and SOL-88871.
With an updated pipeline reference to CRE-931.
This updates the go api test to support broker version 10.3.0.32.
Including the following: 
- semp v2 spec update to version 2.33
- ccsmp native binary update to version 100.0.45.63, to address incorrect broker response introduce around 10.2.0 release.
- updated oauth testing to have configuration oauth server endpoints, updated default oauth test endpoint ports
- address new broker error responses for effected tests
- updated swagger sempv2 code generation
=> Sol 86282 Changes for broker version 10.3 testing

internal/impl/message/outbound_message_impl.go
Added KeepAlive() call to message in DuplicateOutboundMessage to ensure that the message duplication completes before the original message is freed.
=> SOL-86036: Outbound Message with underlying NULL pointer in heavy workload

.github/workflows/test.yml
Updated go version to 1.21.x.  This should be 1.21.4 as of this commit.
=> SOL-78484: Update automation for go version 1.21

pkg/solace/config/messaging_service_properties.go
Changes to native lib removed that limit.
Updated doc strings accordingly.
=> fix: SOL-108125: Updated max cert limit docs 

test/helpers/messaging_service_helpers.go, test/request_reply_message_receiver_test.go
**Changes:**
- SOL-112354: Start and termination of a RequestReplyMessageReceiver integration tests
- feat: updated the tests to fix potential race conditions with the use of time.Millisecond
- feat: added an assertion to check the error returned from replier.Reply in one of the tests
- feat: fixed the failing tests to check that error returns from replier.Reply after service termination
- SOL-112355: Integration tests to cover the requests and responses processing using the RequestReplyMessagePublisher and RequestReplyMessageReceiver
- SOL-112355: updated the integration tests to provide a more consistent test outcome
=> SOL-112355: Integration tests to cover the processing of requests and responses

test/helpers/builder_helpers.go, test/request_reply_message_publisher_test.go
**Changes:**
- added some of the publisher termination integration tests
- added more test cases to cover publisher termination
- refactor: renamed the requestReplyPublisher variable in the integration tests to publisher
=> SOL-112353: Start and termination of a RequestReplyMessagePublisher integration tests

internal/ccsmp/ccsmp_core.go, internal/ccsmp/ccsmp_helper.c, internal/ccsmp/ccsmp_helper.h, internal/impl/core/receiver.go
dispatchMap and go declared C structure (solClient_session_rxMsgDispatchFuncInfo_t) with a pointer within appear to cause stack copying/memory moving problems with CGO.
dispatchMap is totally unnecessary, so remove it.  Move stack allocation of C datastructure to inside the C code, so we pass only primitives and uintptr between Go and C.
=> Bug SOL-114567

internal/ccsmp/ccsmp_core.go, internal/ccsmp/ccsmp_flow.go, internal/ccsmp/ccsmp_helper.c, internal/ccsmp/ccsmp_helper.h, test/messaging_service_test.go
This should completely fix the `fatal error: invalid pointer found on stack` - runtime error within the API. The internal JIRA ticket for this PR is SOL-117431.
**Changes:**
- added a comment that in the NewSessionDispatch function, the `user_p` in the SolClientSessionRxMsgDispatchFuncInfo struct should be set in C if we want to use it
- replaced all usages of the `C.uintptr_to_void_p()` method with direct casts to void* in C
=> SOL-117431: Replaced other uses of the uintptr_to_void_p function to fix runtime error

.github/workflows/test.yml, test/messaging_service_test.go
This PR is to reduce git action execution time that blocks 5 mins on each skipped flaky test.
=> SOL-117804: Part1 tweaking test skip to avoid before and after test execution

.github/workflows/test.yml, test/messaging_service_test.go, test/persistent_receiver_test.go
**Changes:**
- SOL-124616: Isolated the two unstable test cases that causes the panic on Linux musl node
- SOL-124616: fix for upload-artifact Github action. Bumped to version 4
- SOL-124616: added comment on test case that cause pipeline to panic
=> SOL-124616: Go API pipeline fails to build with fatal error: runtime: stack split at bad time on linux musl platforms

test/persistent_receiver_test.go
Changed how queue is deleted so that the helper method uses data indepent of the receiver. Previoulsy this was causing an error because the helper method would occasionally illegally access the receiver's data after it had terminated due to a race condition. Other race conditions in the test such as checking the receiver's state before termination had begun has been mitigated through timers and blocking channel reads/writes. Refer to impl for details.
=> SOL-116360:  Fixed terminaton test

test/helpers/resource_helpers.go, test/persistent_receiver_test.go
Added test to verify that the CCSMP subcode 164 is mapped correctly and is passed to the application through an error when a persistent receiver tries to provision and bind to a non durable queue but uses the name of a pre-existing durable queue.
=> SOL-95364: 400 Invalid Queue Endpoint return code

internal/ccsmp/ccsmp_container.go, internal/ccsmp/ccsmp_core.go, internal/ccsmp/ccsmp_helper.h, internal/ccsmp/ccsmp_message.go, internal/ccsmp/ccsmp_message_tracing.go, internal/ccsmp/cgo_helpers.go, internal/impl/core/error.go, internal/impl/core/events.go, internal/impl/core/receiver.go, internal/impl/core/transport.go, internal/impl/message/inbound_message_impl.go, internal/impl/message/message_impl.go, internal/impl/message/outbound_message_impl.go, internal/impl/publisher/direct_message_publisher_impl_test.go, internal/impl/publisher/persistent_message_publisher_impl_test.go, internal/impl/publisher/request_reply_message_publisher_impl_test.go, internal/impl/receiver/direct_message_receiver_impl_test.go, internal/impl/receiver/persistent_message_receiver_impl.go, internal/impl/receiver/persistent_message_receiver_impl_test.go, internal/impl/receiver/request_reply_message_receiver_impl_test.go
Changed internal error struct used for GetLastErrorInfo so that it only allocates a char array when necessary. Adapted unit tests and helpers to new error struct, mostly around construction. The purpose of this change was to make the memory allocation of error structs within the API more efficient.
=> SOL-98116/EBP-43: Memory Allocation Of Error Structs

Jenkinsfile, test/persistent_receiver_test.go
**Changes:**
- pinned the go version for the linux musl node to 1.22.4
=> EBP-46: pinned the go version for the linux musl node to 1.22.4

version.go
**Changes:**
- EBP-368: bumped up the Go API version to 1.8.0
=> EBP-368: bumped up the Go API version to 1.8.0

internal/ccsmp/ccsmp_message.go, internal/impl/message/inbound_message_impl.go, internal/impl/message/inbound_message_test.go, pkg/solace/message/inbound_message.go, test/cache_test.go, test/message_test.go
**Changes:**
- EBP-24: As a developer, I can retrieve the cache request ID from a cached message
=> EBP-24: As a developer, I can retrieve the cache request ID from a cached message

internal/impl/core/cache_requestor.go, test/cache_test.go
Added a test for verifying wildcard cache request subscriptions for AsAvailable cache requests.
=> EBP-470: Wildcard cache subscriptions

test/cache_test.go
Added test to verify cache response that takes a long time with 100k+ messages in response.
=> EBP-471: cache test for big responses

test/cache_test.go, test/helpers/cache_helpers.go
Added test for verifying that the configured number of max cached messages are received as a result of a cache request.
=> EBP-472: Test for max cached messages

test/cache_test.go, test/helpers/cache_helpers.go
Cache request that require multiple messages (Get Next) in reply.
=> EBP-474: Test for large cached messages

test/cache_test.go, test/helpers/cache_helpers.go
Added test to verify that API gets a supsect message and suspect outcome when at least one message in the cache response is suspect.
=> EBP-480: At least one message in cache reply is suspect.

test/cache_test.go
Added test to verify API behaviour when there is no data to retrieve from the cache.
=> EBP-479: no data in cache reply

test/cache_test.go
Added test to verify that a cache request will fail on an expired timeout.
=> EBP-478: Expired timeout cache test

test/cache_test.go
Added test to verify that subsequent cache requests which request live data on the same on-wildcard topic are rejected if the first cache request is still outstanding.
=> EBP-481: Subsequent non-wildcard cache requests are rejected

.github/workflows/test.yml, internal/ccsmp/ccsmp_cache.go, pkg/solace/resource/destination.go, pkg/solace/resource/destination_test.go, test/cache_test.go, test/helpers/cache_helpers.go
Updated names of cache request strategy variants so they can be more clearly associated with cache operations specifically, rather than be considered a general resource of the API
=> EBP-567: Update Cache Request Strategy Names

test/cache_test.go, test/helpers/cache_helpers.go
This PR is just to fix some test stability issues. We were using a receiver that had a default backpressure of 50 to handle 100000 messages, so some were getting dropped. This was missed in the initial testing because it usually passes locally, and because the default behaviour that the developer who wrote the test was accustomed to a backpressure strategy of elastic being used by default, as is the case in the PS+ Python API. There is no Jira for this fix atm.
=> Cache test stability

test/cache_test.go
Added test to verify that cache requests subsequent to outstanding flow thru request are rejected, except for other flow thru requests.
=> EBP-482: test to validate only flow thru is not rejected while there is outstanding flow thru

internal/impl/core/cache_requestor.go, internal/impl/receiver/message_receiver_impl_test.go
Added unit test which verifies that when certain errors are returned from CCSMP which indicate the the service is reconnecting or otherwise unavailable, the application's attempt to send a cache request is immediately refused with the appropriate error and does not block.
=> EBP-488: Cache requests are non-blocking

.github/workflows/test.yml
Updated test.yml workflow file to use ubuntu 24.04 instead of 20.04 in response to 20.04 brownout in advance of April 15, 2025 deprecation of the older version. An example of the problem that this PR solves can be found at https://github.com/SolaceDev/pubsubplus-go-client/actions/runs/14200170851?pr=114.
=> EBP-751: GHA ubuntu version update

internal/ccsmp/ccsmp_helper.c, test/cache_test.go
I added the test described by the original ticket, which just tested that wildcard topics could be sent in CachedOnly cache requests.
I also added a new test that tests the interaction between a receiver sending CachedOnly cache requests and another receiver receiving messages on the same topic. This test covers a variety of situations where there would be overlapping subscriptions, including:
- sending a cache request on a topic when its receiver is already subscribed to that topic
- sending a cache request on a topic when its receiver was previously subscribed to that topic
- receiving live data on a receiver with a subscription overlapping with a cache request
- receiving live data on a receiver which previously send a cache request with an overlapping subscription
- And others, for a …
=> EBP-711: Added tests verifying behaviour of cached only message filtering on wildcard topics.
