SolaceDev/pubsubplus-go-client

internal/ccsmp/includes_darwin.go
internal/ccsmp/includes_linux.go
internal/ccsmp/lib/include/solclient/solClient.h
internal/ccsmp/lib/include/solclient/solClientDeprecated.h
internal/ccsmp/lib/include/solclient/solClientMsg.h
internal/impl/core/error.go
internal/impl/core/init.go
pkg/solace/subcode/subcode_generated.go
test/data/config/config_testcontainers.json

Update Solace PubSub+ Client for C to 7.23.0

---

internal/impl/publisher/direct_message_publisher_impl.go
internal/impl/publisher/persistent_message_publisher_impl.go

Fixed an issue where multiple goroutines publishing to the same publisher may lead to errors

---

.github/workflows/test.yml
internal/ccsmp/ccsmp_core.go
internal/impl/core/transport.go
internal/impl/messaging_service_builder_impl.go
internal/impl/messaging_service_impl.go
internal/impl/messaging_service_impl_test.go
internal/impl/publisher/direct_message_publisher_impl.go
internal/impl/publisher/persistent_message_publisher_impl.go
internal/impl/receiver/direct_message_receiver_impl.go
internal/impl/receiver/persistent_message_receiver_impl.go
pkg/solace/config/doc.go
pkg/solace/config/message_receiver_strategies.go
pkg/solace/config/messaging_service_strategies.go
pkg/solace/direct_message_publisher.go
pkg/solace/doc.go
pkg/solace/message/sdt/structured_data_types.go
pkg/solace/messaging_service.go
pkg/solace/metrics/metrics.go

Updated Go version to 1.20.
Added a new check to run `go fmt` on commit, failing if any files do not match.
Updated all files with `go fmt` to pass above check.

Updates to Git Actions

---

README.md

Updated Readme for darwin arm64 platform runtime support.

SOL-95448: Updated README.md to include macos arm64 platform support

---

test/helpers/resource_helpers.go
test/partitioned_queue_test.go

Fixed issue were PQ test does nto wait for received messages

SOL-98567: Adjust rebalance delay for partitioned queue tests

---

test/request_reply_message_publisher_test.go
test/request_reply_message_receiver_test.go

**Changes:**
- Instantiation and configuration integration tests for the RequestReplyMessagePublisherBuilder and RequestReplyMessageReceiverBuilder

SOL-112352: RequestReplyMessageBuilders instantiation and configuration integration tests

---

test/helpers/messaging_service_helpers.go
test/request_reply_message_receiver_test.go

**Changes:**
- start and termination of a RequestReplyMessageReceiver integration tests

SOL-112354: Start and termination of a RequestReplyMessageReceiver integration tests

---

internal/ccsmp/ccsmp_message_tracing.go

This should fix [this data race issue](https://github.com/SolaceProducts/pubsubplus-go-client/issues/16). The internal JIRA ticket for this PR is SOL-116516 .
**Changes:**
- feat: fixed the out of bounce read/write access for the traceID and spanID

SOL-116516: fix for the bounce read/write access for traceID and spanID

---

.github/workflows/test.yml

Also bump git action test version to version 1.22.

SOL-117089: Added git action checks for go vet and staticcheck

---

.github/workflows/test.yml

**Changes:**
- build: added step to install docker-compose v1 in Git actions

Fix git actions

---

internal/ccsmp/ccsmp_core.go
internal/ccsmp/ccsmp_endpoint_permissions.go
internal/ccsmp/ccsmp_helper.c
internal/ccsmp/ccsmp_helper.h
internal/impl/constants/default_properties.go
internal/impl/constants/error_strings.go
internal/impl/core/endpoint_provisioner.go
internal/impl/core/endpoint_provisioner_test.go
internal/impl/core/events.go
internal/impl/core/transport.go
internal/impl/messaging_service_impl.go
internal/impl/messaging_service_impl_test.go
internal/impl/provisioner/endpoint_provisioner_impl.go
internal/impl/provisioner/endpoint_provisioner_impl_test.go
internal/impl/receiver/persistent_message_receiver_impl.go
internal/impl/validation/validator.go
pkg/solace/config/endpoint_properties.go
pkg/solace/config/endpoint_properties_test.go
pkg/solace/endpoint_provisioner.go
pkg/solace/messaging_service.go
test/endpoint_provisioner_test.go
test/testcontext/test_context_testcontainers.go
version.go

**Changes:**
- SOL-121556: Golang: Implement code changes to support the endpoint provision feature
- feat[SOL-121556]: fixed failing tests
- SOL-121557: Golang: Implement the endpoint deprovision  feature
- chore: removed some unnecessary comments from some tests
- feat[SOL-121560]: wrote integration tests to provide 100% coverage for the new code changes

SOL-121556: Golang: Implement code changes to support the endpoint provision feature

---

test/helpers/messaging_service_helpers.go

**Changes:**
- test: updated a test helper function to fix a race condition in a test

test: updated a test helper function to fix a race condition in a test

---

test/request_reply_message_publisher_test.go
test/request_reply_message_receiver_test.go

**Changes:**
- fix for the Go api intermittent request reply publisher termination test failures

EBP-45: fix for the Go api intermittent request reply publisher termination test failures

---

internal/impl/core/metrics.go
pkg/solace/metrics/metrics.go
test/metrics_test.go

**Changes:**
- EBP-17: As a developer, I can access updated cache metrics

EBP-17: As a developer, I can access updated cache metrics

---

test/endpoint_provisioner_test.go
test/helpers/messaging_service_helpers.go
test/request_reply_message_receiver_test.go

**Changes:**
- EBP-94: fixed race condition with endpoint provisioner with disconnected messaging service test case

EBP-94: fixed race condition with endpoint provisioner with disconnected messaging service test case

---

test/message_test.go

**Changes:**
- EBP-402: Go API basic publish test failing after timeout

EBP-402: Go API basic publish test failing after timeout

---

test/cache_test.go

Added test to verify that API returns error when given a wildcard topic for cache requests using CachedFirst or LiveCancelsCached configurations.

EBP-467: Wildcard cache requests rejected for CachedFirst and LiveCancelsCached

---

test/cache_test.go
test/helpers/cache_helpers.go

Added test for receiving live data on the same topic as a cache request

EBP-463: Asynchronous cache request with live data

---

internal/ccsmp/ccsmp_session_stats_rx_generated.go
internal/ccsmp/lib/include/solclient/solClient.h
internal/ccsmp/lib/include/solclient/solClientDeprecated.h
internal/ccsmp/lib/include/solclient/solClientMsg.h
internal/ccsmp/lib/licenses.txt

EBP-452: Updated CCSMP to 7.32.0.3

---

test/cache_test.go

Added test verifying that the API receives messages despite a cluster being down.

EBP-477: test for bad cluster

---

test/cache_test.go

Added test to verify max message age for cache request configurations.

EBP-473: Test to verify max cache message age.

---

test/cache_test.go

Added test for verifying that no cached messages are received if none are available from the cache instance.

EBP-475: No cache data available

---

test/persistent_receiver_test.go

**Changes:**
- EBP-401: Go subscription latency test failing due to race condition

EBP-401: Go subscription latency test failing due to race condition

---

pkg/solace/cache_request_outcome.go
pkg/solace/receiver_cache_requests.go
pkg/solace/resource/destination.go

The docs typos are best summarized by the original ticket, EBP-684.

EBP-684: Fixed docs typos.

---

test/README.md
test/go.mod
test/go.sum

Update test/README.md with more isntructions for initial setup. Update github.com/docker/distribution to 2.8.2

EBP-746: Improve build/test environment
